# Generated by Django 4.1.7 on 2023-03-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tema',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
